apiVersion: v1
kind: Service
metadata:
  name: platformnpservice-erv
spec:
  type: NodePort
  selector:
    app: platformservice
  ports:
  - name:  platformservice
    port:  80
    protocol: TCP
    targetPort: 80
    nodePort: 31947